#!/bin/bash
server="$1"
[[ -z "$server" ]] && echo Please specify a server to deploy to. && exit 1

outPath=/tmp/WeddingApp
dotnet publish -c Release -r linux-x64 -o "$outPath" || exit $?

cd $(dirname "$outPath")
outDir=$(basename "$outPath")
zipFile="$outDir.zip"
zip -r "$zipFile" "$outDir"
scp "$zipFile" "$server":/tmp
ssh -t "$server"\
    sudo unzip -o "/tmp/$zipFile" -d /var/lib/weddingapp\
    \&\& cd /var/lib/weddingapp/WeddingApp\
    \&\& sudo --set-home -u weddingapp ./WeddingApp.Cli weddingdb update\
    \&\& sudo ln -fs /var/lib/weddingapp/WeddingApp/WeddingApp.Web.service /etc/systemd/system/WeddingApp.Web.service\
    \&\& sudo systemctl daemon-reload\
    \&\& sudo systemctl enable WeddingApp.Web.service\
    \&\& sudo systemctl restart WeddingApp.Web.service
cd -
