// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingApp.Lib.Data;

namespace WeddingApp.Lib.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20210215024620_AddEmailConfirmationCode")]
    partial class AddEmailConfirmationCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WeddingApp.Lib.Data.EmailConfirmationCode", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("EmailConfirmationCodes");
                });

            modelBuilder.Entity("WeddingApp.Lib.Data.Rsvp", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Rsvps");
                });

            modelBuilder.Entity("WeddingApp.Lib.Data.WebConfiguration", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RsvpPassword")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebConfiguration");
                });

            modelBuilder.Entity("WeddingApp.Lib.Data.EmailConfirmationCode", b =>
                {
                    b.HasOne("WeddingApp.Lib.Data.Rsvp", "Rsvp")
                        .WithOne("ConfirmationCode")
                        .HasForeignKey("WeddingApp.Lib.Data.EmailConfirmationCode", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rsvp");
                });

            modelBuilder.Entity("WeddingApp.Lib.Data.Rsvp", b =>
                {
                    b.Navigation("ConfirmationCode");
                });
#pragma warning restore 612, 618
        }
    }
}
